package org.f1x.message.field;

import org.f1x.util.ByteSequence;

import static org.f1x.util.ByteSequenceWrapper.of;


public class MsgType {

    public static final ByteSequence HEARTBEAT = of("0");
    public static final ByteSequence TEST_REQUEST = of("1");
    public static final ByteSequence RESEND_REQUEST = of("2");
    public static final ByteSequence REJECT = of("3");
    public static final ByteSequence SEQUENCE_RESET = of("4");
    public static final ByteSequence LOGOUT = of("5");
    public static final ByteSequence INDICATION_OF_INTEREST = of("6");
    public static final ByteSequence ADVERTISEMENT = of("7");
    public static final ByteSequence EXECUTION_REPORT = of("8");
    public static final ByteSequence ORDER_CANCEL_REJECT = of("9");
    public static final ByteSequence LOGON = of("A");
    public static final ByteSequence NEWS = of("B");
    public static final ByteSequence EMAIL = of("C");
    public static final ByteSequence ORDER_SINGLE = of("D");
    public static final ByteSequence ORDER_LIST = of("E");
    public static final ByteSequence ORDER_CANCEL_REQUEST = of("F");
    public static final ByteSequence ORDER_CANCEL_REPLACE_REQUEST = of("G");
    public static final ByteSequence ORDER_STATUS_REQUEST = of("H");
    public static final ByteSequence ALLOCATION_INSTRUCTION = of("J");
    public static final ByteSequence LIST_CANCEL_REQUEST = of("K");
    public static final ByteSequence LIST_EXECUTE = of("L");
    public static final ByteSequence LIST_STATUS_REQUEST = of("M");
    public static final ByteSequence LIST_STATUS = of("N");
    public static final ByteSequence ALLOCATION_INSTRUCTION_ACK = of("P");
    public static final ByteSequence DONT_KNOW_TRADE = of("Q");
    public static final ByteSequence QUOTE_REQUEST = of("R");
    public static final ByteSequence QUOTE = of("S");
    public static final ByteSequence SETTLEMENT_INSTRUCTIONS = of("T");
    public static final ByteSequence MARKET_DATA_REQUEST = of("V");
    public static final ByteSequence MARKET_DATA_SNAPSHOT_FULL_REFRESH = of("W");
    public static final ByteSequence MARKET_DATA_INCREMENTAL_REFRESH = of("X");
    public static final ByteSequence MARKET_DATA_REQUEST_REJECT = of("Y");
    public static final ByteSequence QUOTE_CANCEL = of("Z");
    public static final ByteSequence QUOTE_STATUS_REQUEST = of("a");
    public static final ByteSequence MASS_QUOTE_ACKNOWLEDGEMENT = of("b");
    public static final ByteSequence SECURITY_DEFINITION_REQUEST = of("c");
    public static final ByteSequence SECURITY_DEFINITION = of("d");
    public static final ByteSequence SECURITY_STATUS_REQUEST = of("e");
    public static final ByteSequence SECURITY_STATUS = of("f");
    public static final ByteSequence TRADING_SESSION_STATUS_REQUEST = of("g");
    public static final ByteSequence TRADING_SESSION_STATUS = of("h");
    public static final ByteSequence MASS_QUOTE = of("i");
    public static final ByteSequence BUSINESS_MESSAGE_REJECT = of("j");
    public static final ByteSequence BID_REQUEST = of("k");
    public static final ByteSequence BID_RESPONSE = of("l");
    public static final ByteSequence LIST_STRIKE_PRICE = of("m");
    public static final ByteSequence XML_MESSAGE = of("n");
    public static final ByteSequence REGISTRATION_INSTRUCTIONS = of("o");
    public static final ByteSequence REGISTRATION_INSTRUCTIONS_RESPONSE = of("p");
    public static final ByteSequence ORDER_MASS_CANCEL_REQUEST = of("q");
    public static final ByteSequence ORDER_MASS_CANCEL_REPORT = of("r");
    public static final ByteSequence NEW_ORDER_CROSS = of("s");
    public static final ByteSequence CROSS_ORDER_CANCEL_REPLACE_REQUEST = of("t");
    public static final ByteSequence CROSS_ORDER_CANCEL_REQUEST = of("u");
    public static final ByteSequence SECURITY_TYPE_REQUEST = of("v");
    public static final ByteSequence SECURITY_TYPES = of("w");
    public static final ByteSequence SECURITY_LIST_REQUEST = of("x");
    public static final ByteSequence SECURITY_LIST = of("y");
    public static final ByteSequence DERIVATIVE_SECURITY_LIST_REQUEST = of("z");
    public static final ByteSequence DERIVATIVE_SECURITY_LIST = of("AA");
    public static final ByteSequence NEW_ORDER_MULTILEG = of("AB");
    public static final ByteSequence MULTILEG_ORDER_CANCEL_REPLACE = of("AC");
    public static final ByteSequence TRADE_CAPTURE_REPORT_REQUEST = of("AD");
    public static final ByteSequence TRADE_CAPTURE_REPORT = of("AE");
    public static final ByteSequence ORDER_MASS_STATUS_REQUEST = of("AF");
    public static final ByteSequence QUOTE_REQUEST_REJECT = of("AG");
    public static final ByteSequence RFQ_REQUEST = of("AH");
    public static final ByteSequence QUOTE_STATUS_REPORT = of("AI");
    public static final ByteSequence QUOTE_RESPONSE = of("AJ");
    public static final ByteSequence CONFIRMATION = of("AK");
    public static final ByteSequence POSITION_MAINTENANCE_REQUEST = of("AL");
    public static final ByteSequence POSITION_MAINTENANCE_REPORT = of("AM");
    public static final ByteSequence REQUEST_FOR_POSITIONS = of("AN");
    public static final ByteSequence REQUEST_FOR_POSITIONS_ACK = of("AO");
    public static final ByteSequence POSITION_REPORT = of("AP");
    public static final ByteSequence TRADE_CAPTURE_REPORT_REQUEST_ACK = of("AQ");
    public static final ByteSequence TRADE_CAPTURE_REPORT_ACK = of("AR");
    public static final ByteSequence ALLOCATION_REPORT = of("AS");
    public static final ByteSequence ALLOCATION_REPORT_ACK = of("AT");
    public static final ByteSequence CONFIRMATION_ACK = of("AU");
    public static final ByteSequence SETTLEMENT_INSTRUCTION_REQUEST = of("AV");
    public static final ByteSequence ASSIGNMENT_REPORT = of("AW");
    public static final ByteSequence COLLATERAL_REQUEST = of("AX");
    public static final ByteSequence COLLATERAL_ASSIGNMENT = of("AY");
    public static final ByteSequence COLLATERAL_RESPONSE = of("AZ");
    public static final ByteSequence COLLATERAL_REPORT = of("BA");
    public static final ByteSequence COLLATERAL_INQUIRY = of("BB");
    public static final ByteSequence NETWORK_STATUS_REQUEST = of("BC");
    public static final ByteSequence NETWORK_STATUS_RESPONSE = of("BD");
    public static final ByteSequence USER_REQUEST = of("BE");
    public static final ByteSequence USER_RESPONSE = of("BF");
    public static final ByteSequence COLLATERAL_INQUIRY_ACK = of("BG");
    public static final ByteSequence CONFIRMATION_REQUEST = of("BH");
    public static final ByteSequence TRADING_SESSION_LIST_REQUEST = of("BI");
    public static final ByteSequence TRADING_SESSION_LIST = of("BJ");
    public static final ByteSequence SECURITY_LIST_UPDATE_REPORT = of("BK");
    public static final ByteSequence ADJUSTED_POSITION_REPORT = of("BL");
    public static final ByteSequence ALLOCATION_INSTRUCTION_ALERT = of("BM");
    public static final ByteSequence EXECUTION_ACKNOWLEDGEMENT = of("BN");
    public static final ByteSequence CONTRARY_INTENTION_REPORT = of("BO");
    public static final ByteSequence SECURITY_DEFINITION_UPDATE_REPORT = of("BP");

}