package org.f1x.message.field;

import org.f1x.util.ByteSequence;

import static org.f1x.util.ByteSequenceWrapper.of;


public class SecurityType {

    public static final ByteSequence WILDCARD = of("?");
    public static final ByteSequence OTHER_ANTICIPATION_NOTES = of("AN");
    public static final ByteSequence BANKERS_ACCEPTANCE = of("BA");
    public static final ByteSequence BANK_NOTES = of("BN");
    public static final ByteSequence CONVERTIBLE_BOND = of("CB");
    public static final ByteSequence CERTIFICATE_OF_DEPOSIT = of("CD");
    public static final ByteSequence CALL_LOANS = of("CL");
    public static final ByteSequence COMMERCIAL_PAPER = of("CP");
    public static final ByteSequence COMMON_STOCK = of("CS");
    public static final ByteSequence DEPOSIT_NOTES = of("DN");
    public static final ByteSequence GENERAL_OBLIGATION_BONDS = of("GO");
    public static final ByteSequence MUTUAL_FUND = of("MF");
    public static final ByteSequence MANDATORY_TENDER = of("MT");
    public static final ByteSequence PROMISSORY_NOTE = of("PN");
    public static final ByteSequence PREFERRED_STOCK = of("PS");
    public static final ByteSequence TIME_DEPOSIT = of("TD");
    public static final ByteSequence ASSET_BACKED_SECURITIES = of("ABS");
    public static final ByteSequence BILL_OF_EXCHANGES = of("BOX");
    public static final ByteSequence COLLATERALIZED_MORTGAGE_OBLIGATION = of("CMO");
    public static final ByteSequence CORPORATE_PRIVATE_PLACEMENT = of("CPP");
    public static final ByteSequence FEDERAL_AGENCY_COUPON = of("FAC");
    public static final ByteSequence FOREIGN_EXCHANGE_CONTRACT = of("FOR");
    public static final ByteSequence FUTURE = of("FUT");
    public static final ByteSequence IOETTE_MORTGAGE = of("IET");
    public static final ByteSequence LIQUIDITY_NOTE = of("LQN");
    public static final ByteSequence MORTGAGE_BACKED_SECURITIES = of("MBS");
    public static final ByteSequence MORTGAGE_INTEREST_ONLY = of("MIO");
    public static final ByteSequence MORTGAGE_PRINCIPAL_ONLY = of("MPO");
    public static final ByteSequence MORTGAGE_PRIVATE_PLACEMENT = of("MPP");
    public static final ByteSequence MISCELLANEOUS_PASS_THROUGH = of("MPT");
    public static final ByteSequence MEDIUM_TERM_NOTES = of("MTN");
    public static final ByteSequence OPTIONS_ON_FUTURES = of("OOF");
    public static final ByteSequence OPTIONS_ON_PHYSICAL = of("OOP");
    public static final ByteSequence OPTION = of("OPT");
    public static final ByteSequence PRIVATE_EXPORT_FUNDING = of("PEF");
    public static final ByteSequence REVENUE_ANTICIPATION_NOTE = of("RAN");
    public static final ByteSequence REVENUE_BONDS = of("REV");
    public static final ByteSequence SHORT_TERM_LOAN_NOTE = of("STN");
    public static final ByteSequence TAX_ANTICIPATION_NOTE = of("TAN");
    public static final ByteSequence TO_BE_ANNOUNCED = of("TBA");
    public static final ByteSequence US_TREASURY_NOTE2 = of("UST");
    public static final ByteSequence WARRANT = of("WAR");
    public static final ByteSequence _UNKNOWN = of("WLD");
    public static final ByteSequence EXTENDED_COMM_NOTE = of("XCN");
    public static final ByteSequence YANKEE_CERTIFICATE_OF_DEPOSIT = of("YCD");
    public static final ByteSequence CASH = of("CASH");
    public static final ByteSequence CORP_MORTGAGE_BACKED_SECURITIES = of("CMBS");
    public static final ByteSequence CERTIFICATE_OF_OBLIGATION = of("COFO");
    public static final ByteSequence CERTIFICATE_OF_PARTICIPATION = of("COFP");
    public static final ByteSequence CORPORATE_BOND = of("CORP");
    public static final ByteSequence DEBTOR_IN_POSSESSION = of("DINP");
    public static final ByteSequence DUAL_CURRENCY = of("DUAL");
    public static final ByteSequence EURO_CERTIFICATE_OF_DEPOSIT = of("EUCD");
    public static final ByteSequence EURO_COMMERCIAL_PAPER = of("EUCP");
    public static final ByteSequence FEDERAL_AGENCY_DISCOUNT_NOTE = of("FADN");
    public static final ByteSequence LETTER_OF_CREDIT = of("LOFC");
    public static final ByteSequence MULTI_LEG_INSTRUMENT = of("MLEG");
    public static final ByteSequence NO_SECURITY_TYPE = of("NONE");
    public static final ByteSequence PLAZOS_FIJOS = of("PZFJ");
    public static final ByteSequence REPURCHASE = of("REPO");
    public static final ByteSequence REVOLVER_LOAN = of("RVLV");
    public static final ByteSequence TAX_ALLOCATION = of("TAXA");
    public static final ByteSequence PRINCIPAL_STRIP_OF_A_CALLABLE_BOND_OR_NOTE = of("TCAL");
    public static final ByteSequence TAX_EXEMPT_COMMERCIAL_PAPER = of("TECP");
    public static final ByteSequence TERM_LOAN = of("TERM");
    public static final ByteSequence INTEREST_STRIP_FROM_ANY_BOND_OR_NOTE = of("TINT");
    public static final ByteSequence TREASURY_INFLATION_PROTECTED_SECURITIES = of("TIPS");
    public static final ByteSequence PRINCIPAL_STRIP_FROM_A_NON_CALLABLE_BOND_OR_NOTE = of("TPRN");
    public static final ByteSequence TAX_AND_REVENUE_ANTICIPATION_NOTE = of("TRAN");
    public static final ByteSequence US_TREASURY_BILL2 = of("USTB");
    public static final ByteSequence VARIABLE_RATE_DEMAND_NOTE = of("VRDN");
    public static final ByteSequence YANKEE_CORPORATE_BOND = of("YANK");
    public static final ByteSequence BRADY_BOND = of("BRADY");
    public static final ByteSequence EURO_SOVEREIGNS = of("EUSOV");
    public static final ByteSequence OVERNIGHT = of("ONITE");
    public static final ByteSequence PFANDBRIEFE = of("PFAND");
    public static final ByteSequence SPECIAL_ASSESSMENT = of("SPCLA");
    public static final ByteSequence SPECIAL_OBLIGATION = of("SPCLO");
    public static final ByteSequence SPECIAL_TAX = of("SPCLT");
    public static final ByteSequence USD_SUPRANATIONAL_COUPONS = of("SUPRA");
    public static final ByteSequence SWING_LINE_FACILITY = of("SWING");
    public static final ByteSequence US_TREASURY_BILL = of("TBILL");
    public static final ByteSequence US_TREASURY_BOND = of("TBOND");
    public static final ByteSequence US_TREASURY_NOTE = of("TNOTE");
    public static final ByteSequence BRIDGE_LOAN = of("BRIDGE");
    public static final ByteSequence EURO_CORPORATE_BOND = of("EUCORP");
    public static final ByteSequence STRUCTURED_NOTES = of("STRUCT");
    public static final ByteSequence INDEXED_LINKED = of("XLINKD");
    public static final ByteSequence AMENDED_AND_RESTATED = of("AMENDED");
    public static final ByteSequence BUY_SELLBACK = of("BUYSELL");
    public static final ByteSequence DEFAULTED = of("DEFLTED");
    public static final ByteSequence EURO_SUPRANATIONAL_COUPONS = of("EUSUPRA");
    public static final ByteSequence FORWARD = of("FORWARD");
    public static final ByteSequence MATURED = of("MATURED");
    public static final ByteSequence REPLACED = of("REPLACD");
    public static final ByteSequence RETIRED = of("RETIRED");
    public static final ByteSequence REVOLVER_TERM_LOAN = of("RVLVTRM");
    public static final ByteSequence SECURITIES_LOAN = of("SECLOAN");
    public static final ByteSequence WITHDRAWN = of("WITHDRN");
    public static final ByteSequence SECURITIES_PLEDGE = of("SECPLEDGE");

}